
sfTypeSwitcher = {
    "object": "CustomObject",
    "app": "CustomApplication",
    "appMenu": "AppMenu",
    "approvalProcess": "ApprovalProcess",
    "assignmentRules": "AssignmentRules",
    "autoResponseRules": "AutoResponseRules",
    "cls": "ApexClass",
    "community": "Community",
    "component": "ApexComponent",
    "connectedApp": "ConnectedApp",
    "crt": "Certificate",
    "customPermission": "CustomPermission",
    "dashboard": "Dashboard",
    "duplicateRule": "DuplicateRule",
    "dataSource": "ExternalDataSource",
    "email": "EmailTemplate",
    "escalationRules": "EscalationRules",
    "flexipage": "FlexiPage",
    "globalValueSet": "GlobalValueSet",
    "group": "Group",
    "homePageLayout": "HomePageLayout",
    "labels": "CustomLabels",
    "layout": "Layout",
    "letter": "Letterhead",
    "managedTopics": "ManagedTopics",
    "matchingRule": "MatchingRule",
    "network": "Network",
    "object": "CustomObject",
    "objectTranslation": "CustomObjectTranslation",
    "page": "ApexPage",
    "permissionset": "PermissionSet",
    "profile": "Profile",
    "queue": "Queue",
    "quickAction": "QuickAction",
    "remoteSite": "RemoteSiteSettings",
    "reportType": "ReportType",
    "report": "Report",
    "resource": "StaticResource",
    "role": "Role",
    "settings": "Settings",
    "sharingRules": "SharingRules",
    "site": "CustomSite",
    "tab": "CustomTab",
    "translation": "Translations",
    "territory2Type": "Territory2Type",
    "trigger": "ApexTrigger",
    "workflow": "Workflow"
}


AURA_DEFTYPE_EXT = {
    "APPLICATION" : "App.app",
    "CONTROLLER" : "Controller.js",
    "COMPONENT" : ".cmp",
    "EVENT" : "Event.evt",
    "HELPER" : "Helper.js",
    "STYLE" : ".css",
    "DOCUMENTATION" : ".auradoc",
    "RENDERER" : "Renderer.js",
    "DESIGN" : ".design",
    "INTERFACE" : "",
    "PROVIDER" : "",
    "MODEL" : "",
    "TESTSUITE" : "",
    "TOKENS" : "",
    "SVG" : ".svg"
}